#!/bin/bash

echo ""
echo "$(tput setaf 6)        CVESEARCH BY B4GG3R"
echo "$(tput setaf 6)   Usage: cvesearch "Wordpress 4.1""
echo "$(tput setaf 6) YouTube: B4GG3R Twitter: siratsami71"
echo "$(tput setaf 10)"

curl -s -G --data-urlencode "keyword=$1" "https://cve.mitre.org/cgi-bin/cvekey.cgi" | awk -F'"top">' '{print $2}' | sort -u
